theme = "flatwhite"

[editor]
text-width = 128
completion-timeout = 50
rulers = [128]
bufferline = "always"
cursorline = true
cursor-shape.insert = "bar"
indent-guides.render = true
statusline.left = ["mode", "spinner", "spacer", "version-control", "spacer", "file-name", "file-modification-indicator"]
statusline.right = [
  "diagnostics", "selections", "position", "position-percentage", "spacer", "file-encoding", "file-line-ending", "file-type"
]

[keys.normal]
t = { l = ":theme flatwhite", d = ":theme modus_vivendi_transparent" }
