theme = "default"

[keys.normal.space.t]
l = ":theme onelight"
d = ":theme default"

[keys.insert]
C-space = "completion"

[editor]
rulers = [81]
bufferline = "always"
line-number = "relative"
cursorline = true

[editor.indent-guides]
render = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "selections",
  "position",
  "position-percentage",
  "spacer",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
