theme = "default_dusk"

[editor]
lsp.enable              = true
text-width              = 128
completion-timeout      = 50
completion-trigger-len  = 1
rulers                  = [144]
bufferline              = "always"
cursorline              = true
cursor-shape.insert     = "bar"
indent-guides.render    = true
end-of-line-diagnostics = "disable"
default-yank-register   = "+"

[editor.inline-diagnostics]
cursor-line = "disable"

[editor.statusline]
left  = ["mode", "spinner", "spacer", "version-control", "spacer", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "position-percentage", "spacer", "file-encoding", "file-line-ending", "file-type"]

# Toggle
[keys.normal.space.t]
l = ":theme github_light_high_contrast"
d = ":theme darcula-solid"
w = ":toggle soft-wrap.enable"
W = ":toggle whitespace.render all none"

# LSP
[keys.normal.space.l]
f = ":format"
t = ":toggle lsp.enable"
s = ":lsp-stop"
r = ":lsp-restart"
i = ":toggle lsp.display-inlay-hints"
e = ":toggle inline-diagnostics.cursor-line disable error"
E = ":toggle end-of-line-diagnostics disable hint"
