theme = "modus_vivendi_transparent"

[editor]
text-width = 128
idle-timeout = 5
completion-timeout = 5
rulers = [128]
bufferline = "always"
cursorline = true
cursor-shape.insert = "bar"
indent-guides.render = true
statusline.left = ["mode", "spinner", "spacer", "version-control", "spacer", "file-name", "file-modification-indicator"]
statusline.right = [
  "diagnostics", "selections", "position", "position-percentage", "spacer", "file-encoding", "file-line-ending", "file-type"
]

[keys.normal.space]
t = { l = ":theme modus_operandi_tinted", d = ":theme modus_vivendi_transparent" }
i = ":toggle lsp.display-inlay-hints"
