theme = "catppuccin_mocha_transparent"

[editor]
text-width              = 128
completion-timeout      = 50
completion-trigger-len  = 1
rulers                  = [144]
bufferline              = "always"
cursorline              = true
cursor-shape.insert     = "bar"
indent-guides.render    = true
end-of-line-diagnostics = "hint"
default-yank-register   = "+"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left  = ["mode", "spinner", "spacer", "version-control", "spacer", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "position-percentage", "spacer", "file-encoding", "file-line-ending", "file-type"]

[keys.normal.space]
l = { s = ":lsp-stop",                         r= ":lsp-restart",                         i = ":toggle lsp.display-inlay-hints" }
t = { l = ":theme github_light_high_contrast", d = ":theme catppuccin_mocha_transparent", w = ":toggle-option soft-wrap.enable" }
