#=======================================================================#
# JavaScript/TypeScript
#=======================================================================#

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name             = "javascript"
shebangs         = ["deno", "node"]
language-servers = [
  { name = "biome" },
  { name = "deno-lsp",                   except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[[language]]
name             = "typescript"
shebangs         = ["deno", "node"]
language-servers = [
  { name = "biome" },
  { name = "deno-lsp",                   except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[[language]]
name             = "tsx"
shebangs         = ["deno", "node"]
language-servers = [
  { name = "biome" },
  { name = "tailwindcss-ls" },
  { name = "deno-lsp",                   except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[[language]]
name             = "jsx"
shebangs         = ["deno", "node"]
language-servers = [
  { name = "biome" },
  { name = "tailwindcss-ls" },
  { name = "deno-lsp",                   except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[language-server.typescript-language-server]
required-root-patterns = ["package.json", "jsconfig.json", "tsconfig.json"]

# Deno
[language-server.deno-lsp]
command                = "deno"
args                   = ["lsp"]
required-root-patterns = ["deno.json", "deno.jsonc", "deno.lock"]

[language-server.deno-lsp.config.deno]
enable                                      = true
unstable                                    = true
suggest.imports.hosts                       = { "https://deno.land" = true }
inlayHints.parameterNames.enabled           = "all"
inlayHints.parameterTypes.enabled           = true
inlayHints.variableTypes.enabled            = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled  = true
inlayHints.enumMemberValues.enabled         = true

#=======================================================================#
# JSON
#=======================================================================#

[[language]]
name             = "json"
language-servers = [
  { name = "biome" },
  { name = "vscode-json-language-server", except-features = ["format"] },
]

#=======================================================================#
# Markdown
#=======================================================================#

[[language]]
name        = "markdown"
formatter   = { command = "prettier", args = ["--parser", "markdown"] }

#=======================================================================#
# YAML
#=======================================================================#

[[language]]
name        = "yaml"
formatter   = { command = "prettier", args = ["--parser", "yaml"] }

#=======================================================================#
# HTML
#=======================================================================#

[[language]]
name             = "html"
file-types       = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml", "cshtml", "svg"]
language-servers = [
  { name = "tailwindcss-ls" },
  { name = "vscode-html-language-server" },
]

#=======================================================================#
# CSS
#=======================================================================#

[[language]]
name             = "css"
formatter        = { command = "prettier", args = ["--parser", "css"] }
language-servers = [
  { name = "tailwindcss-ls" },
  { name = "vscode-css-language-server", except-features = ["format"] },
]

#=======================================================================#
# Rust
#=======================================================================#

[[language]]
name             = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config]
check.command = "clippy"

#=======================================================================#
# Lua
#=======================================================================#

[[language]]
name             = "lua"
language-servers = ["lua-language-server"]

#=======================================================================#
# PHP
#=======================================================================#

[[language]]
name             = "php"
formatter        = { command = "pretty-php" }
language-servers = ["phpactor"]

[language-server.phpactor]
command = "phpactor"
args    = ["language-server"]
