[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
shebangs = ["deno", "node"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "deno-lsp", except-features = ["format"] },
  "biome",
]

[[language]]
name = "typescript"
shebangs = ["deno", "node"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "deno-lsp", except-features = ["format"] },
  "biome",
]

[[language]]
name = "tsx"
shebangs = ["deno", "node"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "deno-lsp", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
]

[[language]]
name = "jsx"
shebangs = ["deno", "node"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  { name = "deno-lsp", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
]

[language-server.typescript-language-server]
required-root-patterns = ["package.json", "jsconfig.json", "tsconfig.json"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.*"]

[language-server.deno-lsp.config.deno]
enable = true
unstable = true
suggest.imports.hosts = { "https://deno.land" = true }
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled  = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "html"
language-servers = [
  { name = "vscode-html-language-server", except-features = ["format"] },
  "tailwindcss-ls",
]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
language-servers = [
  { name = "vscode-css-language-server", except-features = ["format"] },
  "tailwindcss-ls",
]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "lua"
language-servers = ["lua-language-server"]
auto-format = true
