inherits = "default"

variable = "var"
"variable.parameter" = { fg = "var" }

comment = { fg = "lavender", modifiers = ["italic"] }

"ui.selection" = { bg = "select" }
"ui.selection.primary" = { bg = "select" }
"ui.cursor.match" = { fg = "revolver", bg = "delta" }
"ui.help" = { bg = "delta", fg = "revolver", modifiers = ["bold"] }
"ui.highlight.frameline" = { bg = "frame" }
"ui.debug" = { fg = "debug" }

"diff.minus" = "danger"
"diff.plus" = "success"
"diff.delta" = "delta"

[palette]
lilac = "#70ebde"
lavender = "#51cbbe"
comet = "#5a6269"
bossanova = "#2d3236"
midnight = "#202429"
revolver = "#1a1e23"
var = "#b6f6f0"

select = "#325469"
debug = "#445463"
frame = "#333f49"

danger = "#a9291a"
success = "#377937"
delta = "#59817d"
