inherits = "default"

comment = { fg = "sirocco", modifiers = ["italic"] }

"ui.selection.primary" = { bg = "#325469" }
"ui.cursor.match" = { fg = "#1a1e23", bg = "delta" }

"diff.minus" = "#a9291a"
"diff.plus" = "#377937"
"diff.delta" = "delta"

[palette]
lilac = "#70ebde"
lavender = "#51cbbe"
comet = "#5a6269"
bossanova = "#2d3236"
midnight = "#202429"
revolver = "#1a1e23"
delta = "#59817d"
